<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

/**
 * WP_LoginPress_Assets Class
 *
 * Handles enqueueing of scripts and styles for the LoginPress plugin.
 *
 * @package WP_LoginPress
 * @subpackage WP_LoginPress/includes
 */
class WP_LoginPress_Assets {

    /**
     * Constructor
     *
     * Hooks the enqueue_scripts method to admin_enqueue_scripts.
     */
    public function __construct() {
        // Hook to enqueue admin scripts
        add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_scripts' ] );
    }

    /**
     * Enqueue scripts for LoginPress settings page
     *
     * Loads the React app scripts and localizes data for AJAX and REST API.
     *
     * @param string $hook The current admin page hook suffix.
     */
    public function enqueue_scripts( $hook ) {
        // Only enqueue on LoginPress settings page
        if ( $hook !== 'toplevel_page_loginpress-settings' ) {
            return;
        }

        // Path to the asset file generated by build tools
        $asset_file = plugin_dir_path( dirname( __FILE__ ) ) . 'build/index.asset.php';

        if ( ! file_exists( $asset_file ) ) {
            return;
        }

        // Include asset file to get dependencies and version
        $asset = include $asset_file;

        // Enqueue the main React script
        wp_enqueue_script(
            'wp-loginpress-security-react',
            plugin_dir_url( dirname( __FILE__ ) ) . 'build/index.js',
            $asset['dependencies'],
            $asset['version'],
            true
        );

        // Pass data to JavaScript for AJAX and REST API usage
        wp_localize_script(
            'wp-loginpress-security-react',
            'WP_LOGINPRESS_DATA',
            [
                'ajax_url' => admin_url( 'admin-ajax.php' ),
                'rest_url' => esc_url_raw( rest_url() ),
                'nonce'    => wp_create_nonce( 'wp_rest' ),
            ]
        );
    }
}